spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: ${INVENTORY_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8082
